### ISSUE TITLE
templ generate hangs

### ISSUE THREAD

**Issue by nexovec** [a-h/templ#395] opened 2024-01-04 23:23 UTC
Templ generate generates code but doesn't exit... this happens:

```bash
templ generate
Processing path: /home/nexovec/src/app
(✓) Generated code for "/home/nexovec/src/app/internal/templates/auxiliary.templ" in 8.737188ms
(✓) Generated code for "/home/nexovec/src/app/internal/templates/articles.templ" in 9.527104ms
(✓) Generated code for "/home/nexovec/src/app/internal/templates/common.templ" in 12.512291ms
(✓) Generated code for "/home/nexovec/src/app/internal/templates/app.templ" in 14.644502ms
(✓) Generated code for 4 templates with 0 errors in 15.006609ms
```
and here it freezes up.

This started happening yesterday. templ version: `v0.2.513`, `go version go1.21.5 linux/amd64`

NOTE: I also had trouble migrating to the newest version, was getting errors about a bunch of symbols of templ not being found, but I regenerated everything and it works now. I think I just messed it up somehow myself, just saying in case this reoccurs somewhere else.

**Comment by dougbarrett** [comment] 2024-01-05 05:41
This is also happening to me as well - I'm running templ v0.2.513 and go version go1.21.5 darwin/arm64.

I've stripped it down to a basic template file and am consistently replicating the issue:

```
package components

templ layout() {
    <div>
        hi
    </div>
}
```

**Comment by a-h** [comment] 2024-01-05 09:38
Interesting.... Looks like we've got one example of Linux and another on Mac. Thanks for the info.

I wasn't able to replicate the issue on my ARM64 Mac:

```
1 0 /Users/adrian/github.com/a-h/templ/generator/test-395 % which templ
templ not found
1 1 /Users/adrian/github.com/a-h/templ/generator/test-395 % go install github.com/a-h/templ/cmd/templ@latest
1 0 /Users/adrian/github.com/a-h/templ/generator/test-395 % templ generate
Processing path: /Users/adrian/github.com/a-h/templ/generator/test-395
(✓) Generated code for "/Users/adrian/github.com/a-h/templ/generator/test-395/template.templ" in 1.682083ms
(✓) Generated code for 1 templates with 0 errors in 1.878583ms
1 0 /Users/adrian/github.com/a-h/templ/generator/test-395 %
```

<img width="1512" alt="Screenshot 2024-01-05 at 09 24 05" src="https://github.com/a-h/templ/assets/1029947/5aa2cc57-4423-4714-a22a-aa1d2144bcc3">

To try and replicate the issue, I also tested moving the `test-395` directory into a new project, and creating a new `go.mod` file to check that it wasn't a problem that only happened outside of the templ directory tree. I also tried moving the components into their own subdirectory.

Could you make a complete repro that I can clone to try out please?

The changelog between versions is at: https://github.com/a-h/templ/compare/v0.2.501...v0.2.513 - there's not much between those releases that could affect this. The most likely candidate is parsing the `go.mod` file, since it uses a regexp and there's an infinite `for` loop in there which should exit if it gets to `/`, but I can't reproduce the issue at the moment.

**Comment by polds** [comment] 2024-01-06 01:35
I've hit this on my ARM64 Mac. 

Both latest (0.2.513) and 0.2.501 are exhibiting this for me, but in my case I never get past the `Processing path:` step.
```
$ uname -a
Darwin nomad.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64
$ go version
go version go1.21.5 darwin/arm64
$ go run github.com/a-h/templ/cmd/templ@latest version
v0.2.513
$ go run github.com/a-h/templ/cmd/templ@latest generate -f hello_world.templ
Processing path: 
^C
Cancelling...
^C
$ go run github.com/a-h/templ/cmd/templ@0.2.501 version
v0.2.501
$ go run github.com/a-h/templ/cmd/templ@latest generate -f hello_world.templ
Processing path: 
^C
Cancelling...
^C
```

Interestingly `Cancelling` also gets stuck for me.

**Comment by dougbarrett** [comment] 2024-01-06 06:49
Yea, it appears to be working for me again as well. I'd imagine it was due to the fact that I imported this into an older project, so `go mod tidy` must have been ran between when I last tested and it failed and now after I've tried again.

**Comment by nexovec** [comment] 2024-01-07 00:29
`go mod tidy` didn't solve this for me, nor did recompiling from source. I did this:
```bash
(base) nexovec@pop-os:~/src/templ$ git reset --hard
HEAD is now at d6a0945 docs: document use of React with templ
(base) nexovec@pop-os:~/src/templ$ git pull
Already up to date.
(base) nexovec@pop-os:~/src/templ$ go run ./get-version > .version
cd cmd/templ
go build
(base) nexovec@pop-os:~/src/templ/cmd/templ$ sudo mv templ /home/nexovec/go/bin/templ
[sudo] password for nexovec: 
(base) nexovec@pop-os:~/src/templ/cmd/templ$ templ generate -path ~/src/app/
Processing path: /home/nexovec/src/app/
(✓) Generated code for "/home/nexovec/src/app/internal/templates/articles.templ" in 8.099892ms
(✓) Generated code for "/home/nexovec/src/app/internal/templates/auxiliary.templ" in 8.826067ms
(✓) Generated code for "/home/nexovec/src/app/internal/templates/common.templ" in 11.464812ms
(✓) Generated code for "/home/nexovec/src/app/internal/templates/app.templ" in 15.8433ms
(✓) Generated code for 4 templates with 0 errors in 16.28712ms
^C
Cancelling...
^C
```

**Comment by nexovec** [comment] 2024-01-19 09:58
Could this have priority (I would help, but this bug is way over my head)? It breaks my workflow and will break people's CI as well.

**Comment by a-h** [comment] 2024-01-19 18:09
Yes, need more details. I don't have a reproduction repo at the moment, I'm suspecting it's the same problem as https://github.com/a-h/templ/issues/418

I wanted to write some integration tests for this area, but haven't had chance yet.

**Comment by a-h** [comment] 2024-01-20 01:42
That PR is ready for testing, if people had the time to try it out, that would be great.

**Comment by a-h** [comment] 2024-01-20 11:25
PR has hit the main branch if you want to test from there.

**Comment by nexovec** [comment] 2024-01-23 21:30
The main branch currently doesn't have this issue resolved. What can I do? Run some tools on it? It seems to work fine besides the fact it doesn't terminate.

**Comment by a-h** [comment] 2024-01-25 20:49
I'm still unable to reproduce this issue. If you can provide a sample repo that exhibits the problem, that would help. I'm not sure of the cause.

@nexovec if you've got the issue repeatedly on your machine, I'd be up for a video chat to debug it. 

There's a new release today of https://github.com/a-h/templ/releases/tag/v0.2.543 - upgrade with `go install github.com/a-h/templ/cmd/templ@v0.2.543`

**Comment by nexovec** [comment] 2024-01-29 22:48
@a-h Sorry for late response. After upgrade it seems fixed. Before I close this, do you have any idea what might have solved it?

**Comment by a-h** [comment] 2024-01-30 09:42
Thanks.

I expect it was https://github.com/a-h/templ/pull/441 - sounds like the problem, so I'll close this issue down. There were a few problems with `go.mod` parsing.

The next version completely rewrites the generate command as per https://github.com/a-h/templ/pull/470 so I think a new issue would be warranted if there's any problems with it.

**Closed by a-h** 2024-01-30 09:42 UTC
