### ISSUE TITLE
Don't update files, which have not changed

### ISSUE THREAD

**Issue by guettli** [a-h/templ#377] opened 2023-12-30 20:24 UTC
I would like to use [wgo](https://github.com/bokwoon95/wgo) to run `templ generate` if a file has changed.

But this creates an endless loop, since `templ` updates files, even if nothing has changed.

```
❯ wgo  -file=.go -file=.templ templ generate :: go run main.go 

Processing path: /home/guettli/projects/watchall
(✓) Generated code for "/home/guettli/projects/watchall/ui/index.templ" in 997.999µs
(✓) Generated code for 1 templates with 0 errors in 1.443797ms
Processing path: /home/guettli/projects/watchall
(✓) Generated code for "/home/guettli/projects/watchall/ui/index.templ" in 443.306µs
(✓) Generated code for 1 templates with 0 errors in 706.116µs
Processing path: /home/guettli/projects/watchall
(✓) Generated code for "/home/guettli/projects/watchall/ui/index.templ" in 759.488µs
(✓) Generated code for 1 templates with 0 errors in 1.149856ms
Processing path: /home/guettli/projects/watchall
...
```

The content of the generated file does not change, but with `stat ui/index_templ.go` I see that the file was modified.

I see two ways to break this endless loop:

* wgo keeps a cache of the content instead of watching for file changes.
* templ does not re-generate the foo_templ.go file if nothing has changed.

I think the second solution makes more sense. Maybe it is even faster, since `templ generate` would avoid useless disk io.

Related: https://github.com/a-h/templ/issues/80

**Comment by CalumMackenzie-Chambers** [comment] 2023-12-31 21:54
@guettli I am using [air](https://github.com/cosmtrek/air) rather than wgo but the same principles apply here.

The problem is that you are watching your _templ.go files (which of course change due to the output of templ generate) causing wgo to trigger building again which isn't the behaviour you want. You want to ignore these build files and only include your source .templ files in the watcher. I do this in air with the following line.

`exclude_regex = ["_test.go", ".*_templ.go"]`

Having a quick look at wgo's documentation in the readme you would have to do something similar 

`wgo run -x-file ._templ.go ./cmd/main.go` - I can't test this right now but hopefully with some playing around you will get what you want. 

By ignoring the build files it will only regenerate when you change a source file. 

This will still generate all templates at present (Keep an eye on #80) but this should allow you to have the behaviour you want for the time being.

Hope this helps!

**Comment by bokwoon95** [comment] 2024-01-01 03:30
(I'm the author of wgo) Yup the invocation should be 

```shell
wgo  -file=.go -file=.templ -xfile=_templ.go templ generate :: go run main.go
```

**Comment by guettli** [comment] 2024-01-02 19:34
@bokwoon95 thank you for the hint. I created a PR and added `wgo`: https://github.com/a-h/templ/pull/386

**Comment by a-h** [comment] 2024-01-05 22:15
I'd be up for using the wgo implementation of the hot reload as a package and dropping my implementation if that's an option for the future. It looks relally simple, and well written.

However, the current implementation of wgo doesn't have separation of the wgo command line and the backend, so I can't use it as a package, so that the functionality is included in templ as it stands, and I feel like templ should ship with the following features out of the box (i.e. you shouldn't have to download yet more tools to have things work).

* Watching the `*_templ.go` files, running `templ generate` and re-starting the relevant binary when required.
* On the first time that the watch runs, opening the browser to the right place.
* Providing some way of triggering the browser to reload the current page automatically, so you don't have to press F5.

I'd be OK with automatically telling people to run `go install` to install `wgo` the first time, but I think it would be more complicated to manage starting `wgo` than it would be to use a package.

However... things are going to get a little more complicated, because there's also a cool design coming which will reduce the need to reload the whole binary by having a runtime part that can load strings, see https://github.com/a-h/templ/pull/366

**Comment by a-h** [comment] 2024-01-05 22:16
By the way, I'm also totally allergic to needing config files @bokwoon95 - I love that about wgo. I'm trying to keep templ config free too. 😁

**Comment by a-h** [comment] 2024-01-25 21:12
The version released today includes the new `--watch` mode that makes it so that for HTML changes, you don't need to recompile/restart your app.

**Comment by a-h** [comment] 2024-01-30 09:54
https://github.com/a-h/templ/pull/470 just hit the main branch and will be included in the next release. There's a video which shows how fast the templ `--watch` mode now is if you're just making HTML changes.

The PR is a complete rewrite of the `--watch` mode which includes an `fsnotify` based filesystem watcher.

You'll notice that it carefully avoids updating files that have not changed in https://github.com/a-h/templ/blob/b6e7a779dacbddc4a185023be181fe7349e6b923/cmd/templ/generatecmd/eventhandler.go#L173-L190

Explanation of how to use with other hot reload tools like wgo/air at https://github.com/a-h/templ/pull/470#issuecomment-1914455536

So, I'll close this off.

It would really help if people could test the main branch with your setups, and report back that "everything is OK" (so I know it's been tested by more than just me!), or "it's not working for me".

**Closed by a-h** 2024-01-30 09:54 UTC
