### ISSUE TITLE
WriteString missing

### ISSUE THREAD

**Issue by mathieupost** [a-h/templ#1006] opened 2024-11-28 17:36 UTC
I was trying templ for the first time, but unfortunately I didn't get very far. Following the guide at https://templ.guide/quick-start/creating-a-simple-templ-component I did the following:

1. Setup 
```
mkdir hello-world
cd hello-world
nix develop github:a-h/templ
go mod init github.com/mathieupost/hello-world
go get github.com/a-h/templ
```
2. Created `hello.templ`
```
package main

templ hello(name string) {
	<div>Hello, { name }</div>
}
```
3. Run templ. `templ generate` didn't work as my go bin is not in my path, so I did the following:
```
go get github.com/a-h/templ/cmd/templ
go run github.com/a-h/templ/cmd/templ generate
```

4. Error. The generated file contains this:
<img width="577" alt="image" src="https://github.com/user-attachments/assets/f6b48d94-1f8f-4b60-815e-19c558b3e1d2">

changing that errored line to
```
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(name)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
```
does the trick but of course the generator will overwrite that every time.

**Comment by a-h** [comment] 2024-11-29 17:00
I tried, but was unable to reproduce the issue.

You've provided some of the requested information in the issue template, but not all which may have affected my ability to reproduce it. The issue template asks for `templ info` output which includes templ versions - very useful for debugging and making sure you're using the program you think you are, or a sample repo which might point to the issue in another way.

**Comment by a-h** [comment] 2024-12-27 11:51
By the way, FWIW, `nix develop github:a-h/templ` is not for developing _with_ templ, it's for hacking _on_ templ.

If you want a Nix shell with templ in it, you should run `nix shell github:a-h/templ`. If you want a specific tag of templ, then you can add a tag or commit to the reference, e.g.: `nix shell github:a-h/templ/v0.2.793`

Since I can't reproduce the issue, and you haven't provided any extra info, I'm going to have to close this.

**Closed by a-h** 2024-12-27 11:51 UTC
