### ISSUE TITLE
Binary in`templ_Darwin_arm64.tar.gz` v0.2.697 displays version 0.2.696

### ISSUE THREAD

**Issue by gabrielvincent** [a-h/templ#749] opened 2024-05-20 11:49 UTC
Not sure if the binary is the correct version compilation and only the version info is incorrect, but I got a little confused by this. Here's a video demonstrating:

https://github.com/a-h/templ/assets/469519/fe4bd531-5caa-4b88-8be7-4c074d594d1c

**Comment by joerdav** [comment] 2024-05-20 11:54
This was a small error on the release of this version, @a-h are we going to revoke this tag and re-tag?

**Comment by a-h** [comment] 2024-05-20 12:32
Yes, I think that's sensible.

**Comment by marcelloh** [comment] 2024-05-21 05:40
When ? (Because it complains about a wrong version, when generating)

**Comment by AdrienHorgnies** [comment] 2024-05-21 13:33
I confirmed the issue with another of the artifacts of release v0.2.697:

```console
/tmp/tmp.LmiNrOAo8r 
$ wget https://github.com/a-h/templ/releases/download/v0.2.697/templ_Linux_x86_64.tar.gz
--2024-05-21 15:29:45--  https://github.com/a-h/templ/releases/download/v0.2.697/templ_Linux_x86_64.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/356677177/4a2fa23d-9e4a-4639-b023-caa50c94eb52?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240521%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240521T132835Z&X-Amz-Expires=300&X-Amz-Signature=e7c796acf76c965412c7c4c9f1b79f7b9bc3240c151aa438ac17196cdfbd38b0&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=356677177&response-content-disposition=attachment%3B%20filename%3Dtempl_Linux_x86_64.tar.gz&response-content-type=application%2Foctet-stream [following]
--2024-05-21 15:29:45--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/356677177/4a2fa23d-9e4a-4639-b023-caa50c94eb52?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240521%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240521T132835Z&X-Amz-Expires=300&X-Amz-Signature=e7c796acf76c965412c7c4c9f1b79f7b9bc3240c151aa438ac17196cdfbd38b0&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=356677177&response-content-disposition=attachment%3B%20filename%3Dtempl_Linux_x86_64.tar.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4219557 (4,0M) [application/octet-stream]
Saving to: ‘templ_Linux_x86_64.tar.gz’

templ_Linux_x86_64.tar.gz                           100%[==================================================================================================================>]   4,02M  --.-KB/s    in 0,1s    

2024-05-21 15:29:45 (37,0 MB/s) - ‘templ_Linux_x86_64.tar.gz’ saved [4219557/4219557]

/tmp/tmp.LmiNrOAo8r 
$ ls
templ_Linux_x86_64.tar.gz
/tmp/tmp.LmiNrOAo8r 
$ tar xf templ_Linux_x86_64.tar.gz 
/tmp/tmp.LmiNrOAo8r 
$ ls
LICENSE  README.md  templ  templ_Linux_x86_64.tar.gz
/tmp/tmp.LmiNrOAo8r 
$ ./templ version
v0.2.696
```

**Comment by Depado** [comment] 2024-05-22 08:35
Confirmed on linux too

![image](https://github.com/a-h/templ/assets/694365/80c928dd-6417-4daf-892a-7fa464572007)

**Comment by em1nx** [comment] 2024-05-22 09:28
Confirmed:
```
go install github.com/a-h/templ/cmd/templ@v0.2.697
templ version
v0.2.696
```

**Comment by a-h** [comment] 2024-05-25 08:48
Sorry about the confusion.

I've updated the script that creates the version number to add a check to prevent future mis-tagging.

Today, I've released a new version with a couple of new features and some bug fixes: https://github.com/a-h/templ/releases/tag/v0.2.707 so I think we can close this one as "wont fix" since there's a new release out. I think doing anything else would cause more confusion.

**Closed by a-h** 2024-05-25 08:48 UTC

**Comment by marcelloh** [comment] 2024-05-25 08:57
confirmed (macos)
