### ISSUE TITLE
cmd: `templ generate --watch` don't end `-cmd` on `ctrl+c`

### ISSUE THREAD

**Issue by leandergangso** [a-h/templ#493] opened 2024-02-04 20:36 UTC
If i run the command bellow
`templ generate --watch --proxy="http://localhost:8080" --cmd="go run cmd/app/main.go"`
and the press `ctrl+c` to cancel the command, the `main.go` program is not closing, so in my case i have to run `fuser -k 8080/tcp` to kill my web-server running on the port 8080.

**Comment by a-h** [comment] 2024-02-04 21:21
Thanks for raising this, but I think it's a duplicate of #487.

If you've got time to check out the main branch hot reload behaviour, that would be great, since I've completely rewritten it since the last release.

**Comment by joerdav** [comment] 2024-02-06 11:48
Conversation has moved to #487

**Closed by joerdav** 2024-02-06 11:48 UTC
Labels: bug, cmd, WaitingForMoreInfo
