### ISSUE TITLE
VS Code: Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by johannes-luebke** [a-h/templ#818] opened 2024-06-28 10:44 UTC
This might be a duplicate of #801 , but since that issue is closed and I still experience the problem it might be something different.

The templ extension for VS Code isn't working for me.
On pretty much every keystroke inside a .templ file, even just moving the cursor I get a popup saying:
`Request textDocument/codeAction failed.`

I get highlighting, and I do get Information about functions and structs when I hover over them.
But I don't get any IntelliSense/autocomplete suggestions. And again the error message keeps blinking multiple times a second.

I can give you a minimal repo if you need it, but its really just a basic go mod and a .templ file.
I'm adding all the versions and logs I could gather.
Let me know if you need anything else.

Thank you!

Go: go version go1.22.1 darwin/arm64
Gopls: golang.org/x/tools/gopls v0.16.0
Templ: v0.2.731

[gopls.log](https://github.com/user-attachments/files/16028204/gopls.log)
[templ.log](https://github.com/user-attachments/files/16028205/templ.log)
[vscode.log](https://github.com/user-attachments/files/16028206/vscode.log)

**Comment by joerdav** [comment] 2024-06-28 10:54
Thanks for the thorough report. This is a duplicate of https://github.com/a-h/templ/issues/801 we have a fix underway.

**Closed by joerdav** 2024-06-28 10:54 UTC
