### ISSUE TITLE
lsp: error with special character "@" in the filepath 

### ISSUE THREAD

**Issue by eussam** [a-h/templ#321] opened 2023-12-10 17:30 UTC
Hi,
I'm new to templ and I'm trying to setup a project in VSCode.
I was wondering why I didn't have any syntax highlighting appearing in my .templ files

I followed the documentation to access the log file:

```
{
    ...
    "templ.log": "/Users/michel/logs/vscode-templ.txt",
    ...
}
```

To see that the templ LSP server did not like my filepath `/Users/michel/@DEV/@EUSSAM/@GO/go-vp-web` with the `@` being URL encoded:

```
{"level":"info","ts":"2023-12-10T17:58:15+01:00","caller":"proxy/server.go:712","msg":"client -> server: Hover"}

{"level":"info","ts":"2023-12-10T17:58:15+01:00","caller":"proxy/server.go:68","msg":"updatePosition: not found","uri":"file:///Users/michel/%40DEV/%40EUSSAM/%40GO/go-vp-web/source/hello.templ","from":"4:18"}

{"level":"info","ts":"2023-12-10T17:58:15+01:00","caller":"proxy/server.go:719","msg":"client -> server: Hover end"}
{"level":"info","ts":"2023-12-10T17:58:15+01:00","caller":"proxy/server.go:631","msg":"client -> server: DocumentLink","uri":"file:///Users/michel/%40DEV/%40EUSSAM/%40GO/go-vp-web/source/hello.templ"}
```

It's propably bad habits to use those `@` in my directory structures but I hadn't have any problem with it until now with VSCode and extensions.
I changed directory for the time being to be able to make it work.

Thank you

**Comment by a-h** [comment] 2024-05-12 14:49
Thought I'd investigate this.

With a file structure like the following Go code (no templ involved at all).

```
/Users/adrian/github.com/a-h/package-name-test/@atsymbol/component.go
/Users/adrian/github.com/a-h/package-name-test/go.mod
/Users/adrian/github.com/a-h/package-name-test/main.go
```

You'll end up with issues like this:

<img width="1147" alt="Screenshot 2024-05-12 at 15 31 19" src="https://github.com/a-h/templ/assets/1029947/eb43f675-4223-4d0e-82ca-d1e14abb3e44">

So, within a Go module (i.e. from `go.mod` onwards), you definitely shouldn't have paths that include an at symbol.

But I also decided to check what happened with a `@` higher up in the file path, using templ:

```
/Users/adrian/github.com/a-h/@package-name-test/atsymbol/component.go
/Users/adrian/github.com/a-h/@package-name-test/component.templ
/Users/adrian/github.com/a-h/@package-name-test/component_templ.go
/Users/adrian/github.com/a-h/@package-name-test/go.mod
/Users/adrian/github.com/a-h/@package-name-test/go.sum
/Users/adrian/github.com/a-h/@package-name-test/main.go
```

So, I've got an `@` in the path. However, the LSP is working fine in both the templ file and the Go file with this structure.

`updatePosition: not found` is an info message that's logged if there's a relevant Go position to send to gopls, rather than the hover actually being over templ code. The templ LSP will always log "found" or "not found". It should probably only be logged at debug level, since it's not very informational at all. You can safely ignore it.

However, re-reading what you wrote, I noticed that you said that `I was wondering why I didn't have any syntax highlighting appearing in my .templ files` - and I realised that the syntax highlighting isn't provided by the LSP. It's provided by the VS Code extension.

So, at this point, I'm not really sure what the problem you've got actually is, whether you've sorted it in the meantime, or it's already been fixed by some other activity.

Can you provide a bit more info on the issue, and a more complete reproduction of the issue? Thanks!

**Comment by joerdav** [comment] 2024-05-31 09:51
Closing until further information is provided.

**Closed by joerdav** 2024-05-31 09:51 UTC
Labels: bug, lsp, WaitingForMoreInfo
