### ISSUE TITLE
Formatter messing up script formatting

### ISSUE THREAD

**Issue by adpande** [a-h/templ#540] opened 2024-02-20 07:49 UTC
Hi, In neovim, the formatter is messing up the indentation for script functions. It removed indentation from all the lines from script block. Ideally scripts should be formatted using JS formatting.

**Comment by joerdav** [comment] 2024-02-21 15:28
Hi, I'm sorry you're finding issues with the formatter, could you provide some examples please to aid investigation?

**Comment by eikster-dk** [comment] 2024-02-21 19:07
Hey @joerdav 

I have seen the same behaviour on the latest version of templ. Here's a snippet that ends up with incorrect indentation

```
script Chart() {
    document.addEventListener("DOMContentLoaded", function() {
      const chart = LightweightCharts.createChart("chart", {
        width: 0,
        height: 0,
        layout: {
          background: {
              type: 'solid',
              color: 'rgba(24, 26, 30, 1)',
          },
          textColor: 'rgba(21, 128, 61, 1)',
          lineColor: '#2B2B43',
        },
        grid: {
          vertLines: {
            visible: false,
          },
          horzLines: {
            color: 'rgba(42, 46, 57, 0.5)',
          },
        },
        rightPriceScale: {
          borderVisible: false,
        },
        timeScale: {
          borderVisible: false,
        },
        crosshair: {
          horzLine: {
            visible: false,
          },
        },
        priceScale: {
            mode: 0, // Use mode 0 to disable the ability to zoom and pan
        },
      });

      const revenueSeries = chart.addAreaSeries({
        title: 'revenue',
        topColor: 'rgba(24, 128, 61, 0.56)',
        bottomColor: 'rgba(24, 128, 61, 0.04)',
        lineColor: 'rgba(24, 128, 61, 1)',
        lineWidth: 2,
      });

      const data = [
          { time: '2024-01-01', revenue: 1200, target: 1400 },
          { time: '2024-01-02', revenue: 1400, target: 1500 },
          { time: '2024-01-03', revenue: 1600, target: 1600 },
          { time: '2024-01-04', revenue: 1300, target: 1450 },
          { time: '2024-01-05', revenue: 1100, target: 1300 },
          { time: '2024-01-06', revenue: 1700, target: 1650 },
          { time: '2024-01-07', revenue: 1800, target: 1700 },
          { time: '2024-01-08', revenue: 1900, target: 1750 },
          { time: '2024-01-09', revenue: 1600, target: 1600 },
          { time: '2024-01-10', revenue: 1400, target: 1500 },
          { time: '2024-01-11', revenue: 1350, target: 1450 },
          { time: '2024-01-12', revenue: 1200, target: 1400 },
          { time: '2024-01-13', revenue: 1300, target: 1450 },
          { time: '2024-01-14', revenue: 1400, target: 1500 },
          { time: '2024-01-15', revenue: 1550, target: 1550 },
          { time: '2024-01-16', revenue: 1700, target: 1650 },
          { time: '2024-01-17', revenue: 1800, target: 1700 },
          { time: '2024-01-18', revenue: 1900, target: 1750 },
          { time: '2024-01-19', revenue: 2000, target: 1800 },
          { time: '2024-01-20', revenue: 2100, target: 1850 },
          { time: '2024-01-21', revenue: 2200, target: 1900 },
          { time: '2024-01-22', revenue: 2300, target: 1950 },
          { time: '2024-01-23', revenue: 2400, target: 2000 },
          { time: '2024-01-24', revenue: 2500, target: 2050 },
          { time: '2024-01-25', revenue: 2600, target: 2100 },
          { time: '2024-01-26', revenue: 2700, target: 2150 },
          { time: '2024-01-27', revenue: 2800, target: 2200 },
          { time: '2024-01-28', revenue: 2900, target: 2250 },
          { time: '2024-01-29', revenue: 3000, target: 2300 },
          { time: '2024-01-30', revenue: 3100, target: 2350 },
          { time: '2024-01-31', revenue: 3200, target: 2400 },
      ];

      revenueSeries.setData(data.map(item => ({
        time: item.time,
        value: item.revenue,
        target: item.target,
      })));

      const targetSeries = chart.addLineSeries({
        title: 'Target',
        color: 'rgba(225, 29, 72, 1)',
        lineWidth: 2,
        crossHairMarkerVisible: true,
      });

      // Add data to the target series
      targetSeries.setData(data.map(item => ({
          time: item.time,
          value: item.target,
      })));

      chart.timeScale().fitContent();
    });
}
```

It only happens in the newest version, rolling back to v0.2.513 will correctly format the above snippet again.

**Comment by adpande** [comment] 2024-02-22 07:09
Here is the screenshot of script block before I save and format.

![Screenshot-templ-beforesave](https://github.com/a-h/templ/assets/128881/98250dc1-918f-4996-8596-13138892a837)

And Here it is after I save and templ formats the code.

![Screenshot-templ-aftersave](https://github.com/a-h/templ/assets/128881/741be025-e3a6-43af-99b5-21c24f078954)

Let me know if you need more info.

**Comment by joerdav** [comment] 2024-02-22 08:10
@eikster-dk I'm struggling to reproduce using your example, I've tried both on `@main` and `@v0.2.543` and the indentation is correct.

**Comment by joerdav** [comment] 2024-02-22 08:12
If you both wouldn't mind could you try using the most recent main branch version of templ please? Just to verify that it's not something that's been fixed in the upcoming release.

**Comment by eikster-dk** [comment] 2024-02-22 12:09
ahh yea, well this actually speaks into the other issue I reported yesterday regarding the html-lsp formatter that within LazyVim, at least, runs a sequence of formatting from all LSP's that are attached to the buffer by default (if I understand it correctly) 

After adjusting the settings in conform.nvim to only use templ and ignore other attached LSP's, then it works in the sense that it completely ignores the JS sections and leave it as is, which I can understand from #481 is the correct behaviour.

**Comment by adpande** [comment] 2024-02-22 12:52
@eikster-dk Can you send me the config you did to achieve this in conform.nvim? Thanks for the help!

**Comment by joerdav** [comment] 2024-02-22 13:55
Ah interesting, I suppose I don't have this issue since I don't use the LSP for formatting, so it isn't an issue to have multiple LSPs running.

**Comment by joerdav** [comment] 2024-02-26 11:51
Closing with the resolution of leaving formatting to templ only.

`templ = { "templ" },`

**Closed by joerdav** 2024-02-26 11:51 UTC
Labels: bug, fmt, WaitingForMoreInfo

**Comment by eikster-dk** [comment] 2024-02-27 10:08
Missed the notification but I a lua file called formatters.lua within the plugin folder of LazyVim with the following content:
```
return {
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        templ = { "templ" },
      },
    },
  },
}
```
