### ISSUE TITLE
Error with element attribute  having "::" with value being an expression

### ISSUE THREAD

**Issue by KulvSingh** [a-h/templ#408] opened 2024-01-09 06:26 UTC
hx-on::after-swap={ fmt.Sprintf("htmx.find('#D001').focus()") }

This htmx attribute having "::" with value being an expression is evaluating to be an error as following

cannot use fmt.Sprintf("htmx.find('#D001').focus()") (value of type string) as templ.ComponentScript value in variable declarationcompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)

**Comment by joerdav** [comment] 2024-01-09 16:54
This issue might help you: https://github.com/a-h/templ/issues/397#issuecomment-1879307180

**Comment by a-h** [comment] 2024-01-09 20:02
Duplicate of https://github.com/a-h/templ/discussions/409

**Closed by a-h** 2024-01-09 20:02 UTC
