### ISSUE TITLE
Only for HTML generation? How about Telegram message template?

### ISSUE THREAD

**Issue by TangMonk** [a-h/templ#322] opened 2023-12-11 09:18 UTC

**Comment by a-h** [comment] 2023-12-11 09:37
Yes, the project is only for HTML generation. Currently, supporting SQL, XML or other formats is out of scope.

templ uses context aware escaping, and is based around the concept of parsing templates into an object model which is then used to generate Go code (that's why it renders so quickly, because the runtime is fast). Most of the work is in the parser, and the generator, so the job of supporting other formats would involve writing a whole parser, generator and LSP. The templ language was designed around writing HTML, so I'm not sure how well it would translate into other languages either.

I suppose templ could be modified to be a plugin based system that has multiple parser and generator options from the same CLI, but I don't know if it would save more work than writing a smaller system that takes the ideas of templ and adapts them to telegram templates.

**Closed** 2023-12-14 09:11 UTC
