### ISSUE TITLE
Using this in a template breaks the build for me

### ISSUE THREAD

**Issue by nexovec** [a-h/templ#360] opened 2023-12-24 22:42 UTC
This thing breaks the go build for me but templ generate passes without errors:
```go
templ Contents(){
	<section class="hero" style="background-image:linear-gradient(rgba(20,30,38, 0.9), rgba(24,44,54, 0.8)),url('placehold.co/1280x720'); ">
	</section>
}
```

**Comment by a-h** [comment] 2023-12-25 16:04
How does it break the build? What version? I assume you get an error message?

**Comment by nexovec** [comment] 2023-12-25 18:24
templ version: 0.2.476
go version: go1.21.5 linux/amd64

This is the easiest way I could reproduce this... Create this file in your templates:```go
package templates

script DisplayLoadTime() {
	// Attach the showLoadTime function to the window's load event
}

templ Thing(){

}

templ Contents(){
	<section class="hero" style="background-image:linear-gradient(rgba(20,30,38, 0.9), rgba(24,44,54, 0.8)),url('placehold.co/1280x720'); ">
	</section>
}

templ AnotherThing() {
	@Thing()
}
```
Here already the vscode lsp says `undefined: Thing`.
In my project, these are the last logs:```bash
2023-12-25 19:23:08	building...
2023-12-25 19:23:08	# templates
2023-12-25 19:23:08	internal/templates/test_templ.go:44:24: undefined: Thing
2023-12-25 19:23:08	failed to build, error: exit status 1
```

**Comment by nexovec** [comment] 2023-12-25 18:33
After some further investigation I've narrowed the repro down to:
```go
package templates

script DisplayLoadTime() {
	//'
}

templ Thing(){

}

templ Contents(){
	<any any="url('');">
	</any>
}

templ AnotherThing() {
	@Thing()
}
```

**Comment by nexovec** [comment] 2023-12-25 18:42
I know I've caused some confusion, so here is a link to a repo with a [minimal repro](https://github.com/nexovec/templ-bugreport01)

**Comment by a-h** [comment] 2023-12-25 20:57
Thanks. The minimal reproduction really helps. Looks like the script template parser is tripping over the `//'` sequence.

**Comment by a-h** [comment] 2023-12-25 21:00
The script template parser is here: https://github.com/a-h/templ/blob/main/parser/v2/scripttemplateparser.go

It looks like the issue could be with the expression parser which looks for the close brace, but adding a test to the script template parser is how I'd start to dig in and find out where the issue is.

**Comment by nexovec** [comment] 2023-12-26 00:05
It seems that the character ' is a problem itself, I've encountered the problem again, even when I just do `{`'`}` inside a template.

**Comment by a-h** [comment] 2023-12-26 17:19
OK, I've done some investigation. I couldn't track down `'` being a problem on its own, as evidenced by these unit tests which I added, and were passing...

```go
		{
			name: "template: can contain backtick expressions",
			input: `templ Name() {
	{` + "`" + `}
}`,
			expected: HTMLTemplate{
				Expression: Expression{
					Value: "Name()",
					Range: Range{
						From: Position{
							Index: 6,
							Line:  0,
							Col:   6,
						},
						To: Position{
							Index: 12,
							Line:  0,
							Col:   12,
						},
					},
				},
				Children: []Node{
					Whitespace{Value: "\t"},
					StringExpression{
						Expression: Expression{
							Value: "`",
							Range: Range{
								From: Position{
									Index: 15,
									Line:  1,
									Col:   2,
								},
								To: Position{
									Index: 18,
									Line:  1,
									Col:   3,
								},
							},
						},
					},
				},
			},
```

However, your example clearly shows a problem with parsing comments that contain quote marks of various types within expressions.

I noticed that the expression parser in `parser/v2/expressionparser.go` doesn't check for comments, but it looks for single and double quoted literals. Following this track, I realised that the parser only messes up if there's a single quote in the comment or something, and then a single quote later in the file - it grabs the whole thing as a "string" or "rune" literal.

I've created a branch called `issue_360` and committed what I think is a fix for the issues. I'm stopping for the day now, but if you are able to test parsing and re-generation on your examples based on the contents of that branch, that would be great!

**Comment by nexovec** [comment] 2023-12-27 16:00
``{` + "`" + `}`` doesn't break the code in the original repro, nor does a double quote.

If you've found broken code with double quotes, you should probably post it, because the behavior is not the same for ' and "

**Comment by nexovec** [comment] 2023-12-27 16:14
I built the branch like this:
```bash
go run ./get-version > .version
cd cmd/templ
go build```
then I did ```bash
(base) nexovec@pop-os:~/src/gotest$ ~/src/templ/cmd/templ/templ generate
Processing path: /home/nexovec/src/gotest
(✓) Generated code for "/home/nexovec/src/gotest/test.templ" in 906.498µs
(✓) Generated code for 1 templates with 0 errors in 1.045952ms
(!) templ version check failed: generator v0.2.508 is newer than templ version v0.2.502-0.20231226171507-d2f29ea910a8 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
(base) nexovec@pop-os:~/src/gotest$ go run main.go 
# command-line-arguments
./main.go:11:26: undefined: AnotherThing
```
The behavior is identical to before. It passes `templ generate` and fails on compile. Did I do this correctly?

**Comment by nexovec** [comment] 2023-12-27 16:14
I built the branch like this:
```bash
go run ./get-version > .version
cd cmd/templ
go build```
then I did ```bash
(base) nexovec@pop-os:~/src/gotest$ ~/src/templ/cmd/templ/templ generate
Processing path: /home/nexovec/src/gotest
(✓) Generated code for "/home/nexovec/src/gotest/test.templ" in 906.498µs
(✓) Generated code for 1 templates with 0 errors in 1.045952ms
(!) templ version check failed: generator v0.2.508 is newer than templ version v0.2.502-0.20231226171507-d2f29ea910a8 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
(base) nexovec@pop-os:~/src/gotest$ go run main.go 
# command-line-arguments
./main.go:11:26: undefined: AnotherThing
```
The behavior is identical to before. It passes `templ generate` and fails on compile. Did I do this correctly?

**Comment by a-h** [comment] 2023-12-31 11:29
What you're doing *looks* right, but I don't get the same results on my machine. The warning is spurious, see https://github.com/a-h/templ/issues/355 - there's a bug in the go.mod parsing library due to the change in Go +1.21 which now allows for point versions of Go in go.mod files.

Here's the full set of my session.

```
0 0 /Users/adrian/github.com/a-h/templ % git checkout issue_360
Already on 'issue_360'
Your branch is up to date with 'origin/issue_360'.
0 0 /Users/adrian/github.com/a-h/templ % xc install-snapshot
+ rm -f /Users/adrian/bin/templ
+ rm -f cmd/templ/lspcmd/*.txt
+ go run ./get-version
+ cd cmd/templ
+ go install
0 0 /Users/adrian/github.com/a-h/templ % which templ
/Users/adrian/go/bin//templ
0 0 /Users/adrian/github.com/a-h/templ % cd ~/github.com/nexovec/templ-bugreport01
0 0 /Users/adrian/github.com/nexovec/templ-bugreport01 % templ generate
Processing path: /Users/adrian/github.com/nexovec/templ-bugreport01
(✓) Generated code for "/Users/adrian/github.com/nexovec/templ-bugreport01/test.templ" in 2.419042ms
(✓) Generated code for 1 templates with 0 errors in 2.593666ms
(!) templ version check failed: generator v0.2.510 is newer than templ version v0.2.501 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
0 0 /Users/adrian/github.com/nexovec/templ-bugreport01 % go build ./...
0 0 /Users/adrian/github.com/nexovec/templ-bugreport01 % ./main
```

**Comment by nexovec** [comment] 2024-01-04 23:17
Is any further testing  or help required?

**Comment by a-h** [comment] 2024-01-05 15:43
I was hoping you'd be able to confirm the fix without waiting until the next release, but I'm confident it's sorted in that PR, due to the unit tests.

So, if you have time to test, that would be great, but no problem either way.

**Comment by a-h** [comment] 2024-01-05 15:44
Thanks for the offer, by the way.

**Closed** 2024-01-05 23:06 UTC
