### ISSUE TITLE
VScode extension lsp error

### ISSUE THREAD

**Issue by WanderningMaster** [a-h/templ#227] opened 2023-10-11 19:04 UTC
I'm getting the following error on the extension start up

```[Error - 9:45:21 PM] Client templ: connection to server is erroring. Shutting down server.
[Error - 9:45:21 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
    at LanguageClient.shutdown (/home/andrii/.vscode/extensions/a-h.templ-0.0.14/node_modules/vscode-languageclient/lib/common/client.js:914:1)
    at LanguageClient.stop (/home/andrii/.vscode/extensions/a-h.templ-0.0.14/node_modules/vscode-languageclient/lib/common/client.js:885:1)
    at LanguageClient.stop (/home/andrii/.vscode/extensions/a-h.templ-0.0.14/node_modules/vscode-languageclient/lib/node/main.js:150:1)
    at LanguageClient.handleConnectionError (/home/andrii/.vscode/extensions/a-h.templ-0.0.14/node_modules/vscode-languageclient/lib/common/client.js:1146:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 9:45:21 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 9:45:21 PM] templ client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 9:45:21 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by a-h** [comment] 2023-10-11 20:28
Hi, is the templ binary in your system path? The VS Code extension requires the binary to be present.

You can check this by opening a terminal and running 'templ'.

If it prints out some help, then it's OK.

If you're on Windows you need to worry about whether you're running with WSL or Windows itself. And you would likely need to have templ installed inside any VS Code Devcontainer you've got running.

**Comment by alexpower2002** [comment] 2023-10-11 21:30
Same problem here. Just installed it on macOS. It's in path and outputs help.

[Error - 02:27:31] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 02:27:31] Connection to server got closed. Server will not be restarted.
[Error - 02:27:31] templ client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 

I've got EPIPE message too but not this time.

**Comment by alexpower2002** [comment] 2023-10-11 21:31
Downgrading one release didn't help.

**Comment by a-h** [comment] 2023-10-13 07:44
Interesting. I'm on MacOS (M1), and haven't been able to reproduce it.

Not sure what your timezones are, but I can be available for a Google Meet to try and work out what's going on with it?

**Comment by kingjulienboss** [comment] 2023-10-14 20:47
hi @a-h 

same problem here on kubuntu 22.04 using vscode:

```
[Error - 22:39:50] Client templ: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 22:39:50] Client templ: connection to server is erroring.
write EPIPE
[Error - 22:39:50] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/lev/.vscode/extensions/a-h.templ-0.0.15/dist/main.js:6707:19)
	at LanguageClient.stop (/home/lev/.vscode/extensions/a-h.templ-0.0.15/dist/main.js:6678:21)
	at LanguageClient.stop (/home/lev/.vscode/extensions/a-h.templ-0.0.15/dist/main.js:15874:22)
	at LanguageClient.handleConnectionError (/home/lev/.vscode/extensions/a-h.templ-0.0.15/dist/main.js:6939:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 22:39:50] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 22:39:50] templ client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 22:39:50] Connection to server got closed. Server will not be restarted.
[Error - 22:39:50] Server process exited with code 1.
```

I used the latest release from github and moved the binary to /usr/local:

lev@HP-ENVY-x360-Convertible-13-ay0xxx:~/Downloads$ whereis templ
templ: /usr/local/bin/templ

I also tried with go install but that didn't resolved issue.

Would be open to a Google Meet on weekends. My TZ is Europe/Zurich

**Comment by kingjulienboss** [comment] 2023-10-14 20:50
hi @a-h

I restarted vscode with a logfile. The following output i shown:

```
{"level":"info","ts":"2023-10-14T22:39:50+02:00","caller":"lspcmd/main.go:74","msg":"lsp: starting up..."}
{"level":"info","ts":"2023-10-14T22:39:50+02:00","caller":"lspcmd/main.go:81","msg":"lsp: starting gopls..."}
{"level":"error","ts":"2023-10-14T22:39:50+02:00","caller":"lspcmd/main.go:87","msg":"failed to start gopls","error":"cannot find gopls on the path (\"/home/lev/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin\"), you can install it with `go install golang.org/x/tools/gopls@latest`","stacktrace":"github.com/a-h/templ/cmd/templ/lspcmd.run\n\t/Users/adrian/github.com/a-h/templ/cmd/templ/lspcmd/main.go:87\ngithub.com/a-h/templ/cmd/templ/lspcmd.Run\n\t/Users/adrian/github.com/a-h/templ/cmd/templ/lspcmd/main.go:54\nmain.lspCmd\n\t/Users/adrian/github.com/a-h/templ/cmd/templ/main.go:157\nmain.main\n\t/Users/adrian/github.com/a-h/templ/cmd/templ/main.go:50\nruntime.main\n\t/nix/store/56n7n0r582p01ksr36s7alsxwkmladrm-go-1.21.0/opt/go/src/runtime/proc.go:267"}
```

hope that helps

**Comment by kingjulienboss** [comment] 2023-10-14 21:06
Hey there

I fixed the issue like that:

1. Install gopls `go install golang.org/x/tools/gopls@latest`
2. Go into the terminal and find out where gopls is installed:
```
lev@HP-ENVY-x360-Convertible-13-ay0xxx:~$ whereis gopls
gopls: /home/lev/gocode/bin/gopls
```
In my case it was installed inside the folder */home/lev/gocode/bin* that wasn't added to the PATH variable.
So i added it to the global profile:
Edit file */etc/profile* and add the following snippet to the end of the file:
```
export PATH=$PATH:/your/go/bin/path/from/whereis
```

In my case it looked like that after adding the line.

![grafik](https://github.com/a-h/templ/assets/147748708/b158e2c4-da1f-4f3b-8410-c767b644e568)

I hope this resolves your issues too!

**Comment by a-h** [comment] 2023-10-15 13:37
Thanks @kingjulienboss - @alexpower2002 / @WanderningMaster - is that the same issue for you?

The troubleshooting steps are:

# Check that go, gopls and templ are installed and are present in the path.

```
which go gopls templ
```

You should see 3 lines returned, showing the location of each binary:

```
/run/current-system/sw/bin/go
/Users/adrian/go/bin/gopls
/Users/adrian/bin/templ
```

# Enable LSP logging

Use the "Preferences: Open User Settings (JSON)" command in VS Code and enable logging in templ.

```js
{
    // More settings...
    "templ.log": "/Users/adrian/logs/vscode-templ.txt",
    "templ.goplsLog": "/Users/adrian/logs/vscode-gopls.txt",
    "templ.http": "localhost:7575",
    "templ.goplsRPCTrace": true,
    "templ.pprof": false,
    // More stuff...
}
```

# Start up the project and include the logs

Bear in mind that your code will be included in the logs. Try to make a minimal reproduction if possible.

**Comment by WanderningMaster** [comment] 2023-10-15 21:36
Thank you all guys @a-h @kingjulienboss, at least for me copying `gopls` binary to `/usr/bin` did the trick

**Comment by laneherby** [comment] 2023-10-17 01:13
My `which go gopls templ` on ubuntu returns
```
/usr/local/go/bin/go
/home/herby/go/bin/gopls
/home/herby/go/bin/templ
```

But the error I get when trying to start the lsp is 
```
[Error - 1:11:31 AM] templ client: couldn't create connection to server.
Launching server using command templ failed. Error: spawn templ ENOENT
```

Do I need to set something up differently?

**Comment by kingjulienboss** [comment] 2023-10-17 06:20
@laneherby you can check if the path /home/herby/go/bin is included in $PATH.
You can check using `echo $PATH`.

**Comment by laneherby** [comment] 2023-10-18 01:17
> @laneherby you can check if the path /home/herby/go/bin is included in $PATH. You can check using `echo $PATH`.
@kingjulienboss 
```
echo $PATH
/usr/local/go/bin:/home/herby/.vscodium-server/bin/a5004432af6600c99fa4f918a3f2f8df44df71e6/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/herby/go/bin
```

That's it at the end, the gopls is stored in that directory. I can run this command from my terminal and it works:
```
templ lsp -goplsLog /home/herby/logs/vscode-gopls.txt -log /home/herby/logs/vscode-templ.txt
```

FYI I'm using vscode on windows and using the ssh remote code to work on my linux server. All of the templ stuff is installed on the linux server and running off there.

**Comment by fedevilensky** [comment] 2023-10-20 15:40
I'm having the same issue in arch. When running from the terminal, I can launch the lsp. When using the vs code extension, it can't find the `templ` command

**Comment by Evert-Arends** [comment] 2023-10-27 15:07
I am having a related issue on arch:
```[Error - 5:04:57 PM] templ client: couldn't create connection to server.
Launching server using command templ failed. Error: spawn templ ENOENT```

https://berms.onlyfans.je/cb0c7ff4-7cfa-4f71-ac09-630b41f7bf13.png

**Comment by Evert-Arends** [comment] 2023-10-27 15:10
> I'm having the same issue in arch. When running from the terminal, I can launch the lsp. When using the vs code extension, it can't find the `templ` command

@fedevilensky 

My issues seem to resolve when I start vscode from the bash shell instead of zsh:
```
/bin/bash
code-oss
```

I don't have time to dig, but I assume that it has to do with .bashrc environment variables.

**Comment by a-h** [comment] 2023-10-27 15:36
Ah, that's interesting! I wonder if the PATH variable is not updated to include your `~/go/bin` directory (or wherever you installed Go) in your `.zshrc`, but is in the `.bashrc`.

**Comment by fedevilensky** [comment] 2023-10-27 19:22
I could replicate the behavior. But my .bashrc is pretty much empty. I'm not setting $PATH in it, it's inheriting it from my zsh session

**Comment by a-h** [comment] 2023-11-14 20:28
I've relrased version v0.0.16 of the templ-vscode extension that does more probing for the templ executable, and displays an error message that displays the paths it probed.

https://github.com/templ-go/templ-vscode/commit/47fb4efd355686a9de81cab0abab12fdf427e335

This should help with debugging. For example, if I delete templ from my system, I see this:

<img width="589" alt="Screenshot 2023-11-14 at 20 17 03" src="https://github.com/a-h/templ/assets/1029947/2e1679f9-0e68-4059-979c-f8ff3dec710b">

Is anyone still having trouble? If so, if they could give it a shot, it should help with understanding the issue.

**Comment by cornelius-99** [comment] 2023-11-17 12:54
I had same problems with the plugin for Goland. I Fixed it with the following steps:

1. Make sure `go` is installed globally (not only in Goland IDE)
2. Make sure the $PATH includes the folder that `go install` installs the binaries to. (for me it was /User/<username>/go/bin)
3. Make sure `gopls` is also manually installed

maybe it would be nice to have a error message that gopls needs to be installed when starting the lsp server, otherwise it just exits without any message

**Comment by a-h** [comment] 2023-11-17 14:54
I updated the `templ lsp` command to give a better error message a few days ago: https://github.com/a-h/templ/blob/16dfaad6b1dbf61fbd786c5f098954f63174fcae/cmd/templ/lspcmd/pls/main.go#L45-L59

However, now I'm looking at it again, I realised that I forgot about Windows users, and should probably do something for `.exe` too. I'll take a PR if anyone's got spare time on their hands!

**Comment by a-h** [comment] 2023-11-20 09:02
I've updated the probing to include checks for `gopls.exe` as well as `gopls` in https://github.com/a-h/templ/commit/b6f0b3dad93a476f82657cf778ce7f7cef618752

**Comment by a-h** [comment] 2024-01-05 23:18
I added some more probing locations in https://github.com/templ-go/templ-vscode/commit/34543ff8688cac6bcb9905a5645ee61fa9414e95

I'm going to close this one, and ask for people to open up a new issue, since I think these recent changes have squashed the issue (haven't got any similar reports recently).

**Closed by a-h** 2024-01-05 23:18 UTC
